### ISSUE TITLE
Add Database CD

### ISSUE THREAD

**Issue by stephend017** [stephend017/discord_ritoman#14]
add support for database cd. this means that tables should be updated and preserved on a new deployment.

**criteria for db redeployment**
- all existing data must be saved
- existing fields may not be removed
- only new fields may be added to a table
- new fields must be optional (nullable)

**tasks**
- [ ] remove db dummy data scripts
- [ ] create pandas script to run before starting application
  - [ ] save all user data locally (backup)
  - [ ] save old tables into pandas
  - [ ] validate that new tables do not break above constraints
  - [ ] if new tables are valid then drop old tables
  - [ ] create new tables
  - [ ] save existing data to new tables
- [ ] update `ecosystem.config.js`

**Comment by stephend017** [comment]
moved to #67
